// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnivehjrnhklupqbarmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduaXZlaGpybmhrbHVwcWJhcm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDg4MzIsImV4cCI6MjA2MTMyNDgzMn0.l5nddrPeb8g3fS0lXTuD9X75B-3jeRdoZPnQgqUXgns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);